<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Joelle Fitzgerald">
<meta name="dcterms.date" content="2022-11-27">

<title>JoelleFitzgerald_HIDS502_FinalProject</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="JoelleFitzgerald_HIDS502_FinalProject_files/libs/clipboard/clipboard.min.js"></script>
<script src="JoelleFitzgerald_HIDS502_FinalProject_files/libs/quarto-html/quarto.js"></script>
<script src="JoelleFitzgerald_HIDS502_FinalProject_files/libs/quarto-html/popper.min.js"></script>
<script src="JoelleFitzgerald_HIDS502_FinalProject_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="JoelleFitzgerald_HIDS502_FinalProject_files/libs/quarto-html/anchor.min.js"></script>
<link href="JoelleFitzgerald_HIDS502_FinalProject_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="JoelleFitzgerald_HIDS502_FinalProject_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="JoelleFitzgerald_HIDS502_FinalProject_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="JoelleFitzgerald_HIDS502_FinalProject_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="JoelleFitzgerald_HIDS502_FinalProject_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">JoelleFitzgerald_HIDS502_FinalProject</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Joelle Fitzgerald </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 27, 2022</p>
    </div>
  </div>
    
  </div>
  

</header>

<section id="hids-502-final-project-qi-analyst" class="level1">
<h1>HIDS 502 Final Project: QI Analyst</h1>
<section id="prevention-of-emergency-department-hospital-admissions-in-congestive-heart-failure-chf-patients-through-routine-nutritionist-counseling-a-pilot-quality-improvement-program." class="level2">
<h2 class="anchored" data-anchor-id="prevention-of-emergency-department-hospital-admissions-in-congestive-heart-failure-chf-patients-through-routine-nutritionist-counseling-a-pilot-quality-improvement-program.">Prevention of emergency department hospital admissions in Congestive Heart Failure (CHF) patients through routine nutritionist counseling: a pilot quality improvement program.</h2>
<section id="group-b-joelle-fitzgerald-adam-li-ansel-yuan-lian" class="level3">
<h3 class="anchored" data-anchor-id="group-b-joelle-fitzgerald-adam-li-ansel-yuan-lian">Group B – Joelle Fitzgerald, Adam Li, Ansel (Yuan) Lian</h3>
<section id="qi-analyst-joelle-fitzgerald" class="level4">
<h4 class="anchored" data-anchor-id="qi-analyst-joelle-fitzgerald">QI Analyst: Joelle Fitzgerald</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)     <span class="co"># loads the tidyverse tools</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RPostgres)     <span class="co"># loads the database driver for PostgreSQL</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(connections)   <span class="co"># helps RPostgres work with RStudio</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(keyring)       <span class="co"># access to a local encrypted keychain for passwords</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>con <span class="ot">&lt;-</span> <span class="fu">connection_open</span>(RPostgres<span class="sc">::</span><span class="fu">Postgres</span>(),</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">dbname =</span> <span class="st">"syntheticMGUH2022"</span>,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">host =</span> <span class="st">"35.199.26.47"</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">user =</span> <span class="st">"hids502_student"</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">password =</span> <span class="fu">key_get</span>(<span class="at">service =</span> <span class="st">"syntheticmguh"</span>, </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>                             <span class="at">username =</span> <span class="st">"hids502_student"</span>),</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">bigint =</span> <span class="st">"numeric"</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Use this to set a default connection for every SQL chunk</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># There seems to be some sort of bug in Quarto that requires this</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">connection =</span> <span class="st">"con"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Congestive Heart Failure (CHF) is a progressive, terminal disease characterized by weakening of the heart muscle and impaired pumping of blood to the organs of the body. When the heart cannot pump effectively and is weakened, an individual progressively experiences diminishing energy levels, decreased ability to perform activities of daily living, impaired mobility, and symptoms of organ failure including shortness of breath (American Heart Association, 2019). The Centers for Disease Control and Prevention (CDC) (2022) reports that approximately 6.2 million adults in the United States have been diagnosed with CHF. Care for exacerbations of CHF is typically emergent and expensive. Severe symptoms of CHF leading to hospitalization often result from avoidable behaviors and lifestyle choices such as high dietary sodium leading to excessive water retention, overexertion that leads to unexpected fatigue, and lack of adherence to prescribed medications (Tsuyuki et al., 2001). The estimated incremental national expenditure of CHF care and medications in the United States is approximately $22.3 billion each year (Bhatnagar, Roshni, et al., 2022). Additionally, costs associated with hospital readmissions within 30 days are not reimbursed (US Centers for Medicare and Medicaid, 2019).</p>
<p>Knowing this, it is important CHF patient care is aimed at providing sufficient patient education and prompt intervention to prevent emergent CHF patient hospital admissions and unnecessary expenditures that place a strain on the hospital system and patient wellbeing. Our pilot program aims to identify Congestive Heart Failure patients who may be at-risk for hospital readmission and coordinate routine nutritionist counseling for a heart healthy diet as a new standard of preventative care. With this implementation of preemptive dietary counseling, we strive to increase patient compliance for following a low sodium diet avoiding possible fluid overload, and ultimately reducing a patient’s risk for emergency hospital admission related to severe CHF symptoms.</p>
</section>
<section id="patient-population" class="level2">
<h2 class="anchored" data-anchor-id="patient-population">Patient Population</h2>
<p>Deficiency/Issue Addressed: CHF patients at-risk for emergency hospital admission due to inadequate CHF care management and lifestyle behaviors, specifically dietary compliance.</p>
<p>To identify patients who may benefit from dietary counseling to avoid CHF symptom excerbation and disease progression, we will be looking at patients who have a CHF careplan, CHF diagnosed condition, and/or encounter note indicating CHF as a current problem. From this cohort, we will identify evidence that a patient may be at risk for CHF exacerbation indicating need for intervention such as body weight changes, imbalanced sodium levels, recent blood pressure measurements, and recent ED visit.</p>
<p>With evidence of possible mismanaged disease in our CHF patient cohort, we can extract demographic, lifestyle, and medication information that may also be relevant when describing the current state our patient population.</p>
<section id="initial-patient-population-chf-careplan-diagnosed-condition-and-encounter-note" class="level3">
<h3 class="anchored" data-anchor-id="initial-patient-population-chf-careplan-diagnosed-condition-and-encounter-note">Initial Patient Population: CHF Careplan, Diagnosed Condition, and Encounter Note</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- finding total congestive heart failure patient count --</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co">-- creating CTE to hold CHF patient population including all patients that have a careplan, diagnosed condition, and/or encounter note indicating CHF --</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> CHF_patients <span class="kw">AS</span> (</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> careplans </span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> careplans.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span> <span class="kw">OR</span> careplans.reasoncode <span class="op">=</span> <span class="st">'88805009'</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>   <span class="co">-- Union statement to combine CHF patient careplans with patients diagnosed with CHF condition --</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    <span class="kw">UNION</span> </span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> conditions </span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> conditions.description <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="co">-- Union statement to combine CHF patient careplans and patients diagnosed with CHF condition with CHF patient encounters --</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="kw">UNION</span> </span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> encounters</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> encounters.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span> <span class="kw">OR</span> encounters.reasoncode <span class="op">=</span> <span class="st">'88805009'</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>  <span class="co">-- Union statement to combine CHF patient careplans and patients diagnosed with CHF condition with CHF patient notes --</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>  <span class="kw">UNION</span> </span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>   <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> notes</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> notes.note_text <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a><span class="co">-- returns total CHF patient count --</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> (<span class="kw">select</span> <span class="fu">count</span>(<span class="kw">distinct</span>(CHF_patients)) <span class="kw">as</span> pt_count) <span class="kw">FROM</span> CHF_patients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table class="table table-sm table-striped">
<caption>1 records</caption>
<thead>
<tr class="header">
<th style="text-align: right;">pt_count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">847</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- returns the code for CHF --</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> reasoncode</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> careplans </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> careplans.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table class="table table-sm table-striped">
<caption>Displaying records 1 - 10</caption>
<thead>
<tr class="header">
<th style="text-align: right;">reasoncode</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">88805009</td>
</tr>
<tr class="even">
<td style="text-align: right;">88805009</td>
</tr>
<tr class="odd">
<td style="text-align: right;">88805009</td>
</tr>
<tr class="even">
<td style="text-align: right;">88805009</td>
</tr>
<tr class="odd">
<td style="text-align: right;">88805009</td>
</tr>
<tr class="even">
<td style="text-align: right;">88805009</td>
</tr>
<tr class="odd">
<td style="text-align: right;">88805009</td>
</tr>
<tr class="even">
<td style="text-align: right;">88805009</td>
</tr>
<tr class="odd">
<td style="text-align: right;">88805009</td>
</tr>
<tr class="even">
<td style="text-align: right;">88805009</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- returns total count of patients with CHF established care plans --</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">count</span>(<span class="kw">distinct</span> patient)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> careplans </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> careplans.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span> <span class="kw">OR</span> careplans.reasoncode <span class="op">=</span> <span class="st">'88805009'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table class="table table-sm table-striped">
<caption>1 records</caption>
<thead>
<tr class="header">
<th style="text-align: right;">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">842</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- returns total count of patients with CHF as a diagnosed condition --</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">count</span>(<span class="kw">distinct</span> patient)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> conditions </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> conditions.description <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table class="table table-sm table-striped">
<caption>1 records</caption>
<thead>
<tr class="header">
<th style="text-align: right;">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">847</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- returns total count of patients with CHF medical notes --</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">count</span>(<span class="kw">distinct</span> patient)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> notes </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> note_text <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table class="table table-sm table-striped">
<caption>1 records</caption>
<thead>
<tr class="header">
<th style="text-align: right;">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">847</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>There are a total of 847 patients in the Synthea database that have a diagnosed condition, careplans, and/or encounter note indicative of CHF. 842 patients have an established care plan for managing their CHF while 5 patients do not have careplans, but have had CHF noted as a diagnosed condition or in an encounter note.</p>
</section>
<section id="chf-patient-body-weight-management" class="level3">
<h3 class="anchored" data-anchor-id="chf-patient-body-weight-management">CHF Patient Body Weight Management</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">--- add drop table if exists to refresh temporary table created ---</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="kw">DROP</span> <span class="kw">TABLE</span> <span class="cf">IF</span> <span class="kw">EXISTS</span> CHF_patients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- local table to hold initial patient population identified to have a diagnosis of CHF --</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">LOCAL</span> TEMP <span class="kw">TABLE</span> CHF_patients <span class="kw">AS</span> (</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> careplans </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> careplans.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span> <span class="kw">OR</span> careplans.reasoncode <span class="op">=</span> <span class="st">'88805009'</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">UNION</span> </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> conditions </span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> conditions.description <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="kw">UNION</span> </span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>   <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> notes</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> notes.note_text <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- local table 'patient_weights' returns body weight observations for each patient where not null --</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">LOCAL</span> TEMP <span class="kw">TABLE</span> patient_weights <span class="kw">AS</span> (</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="kw">SELECT</span> weights.<span class="op">*</span> </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="kw">FROM</span> (</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="co">-- finding CHF patients with body weight observation recorded --</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">DISTINCT</span> patient <span class="kw">FROM</span> observations </span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">WHERE</span> description <span class="kw">LIKE</span> <span class="st">'%Body Weight%'</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    <span class="kw">AND</span> patient <span class="kw">in</span> (<span class="kw">SELECT</span> <span class="op">*</span> <span class="kw">FROM</span> CHF_patients)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  ) patients</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="co">-- using a lateral join (researched on Google in collaboration with teammates) to combine results from query above matching CHF patients with body weight recorded at an encounter --</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  <span class="kw">JOIN</span> LATERAL (</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="op">*</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    <span class="kw">FROM</span> observations </span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    <span class="kw">WHERE</span> observations.patient <span class="op">=</span> patients.patient</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    <span class="kw">AND</span> description <span class="kw">LIKE</span> <span class="st">'%Body Weight%'</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>    <span class="kw">AND</span> patient <span class="kw">in</span> (<span class="kw">SELECT</span> <span class="op">*</span> <span class="kw">FROM</span> CHF_patients)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>    <span class="kw">ORDER</span> <span class="kw">BY</span> observations.<span class="dt">date</span> <span class="co">-- ordering by observation date --</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>    <span class="kw">LIMIT</span> <span class="dv">2</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>  ) weights <span class="kw">ON</span> <span class="kw">TRUE</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- visualizing patient_weights CTE created above --</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="op">*</span> <span class="kw">FROM</span> patient_weights</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table class="table table-sm table-striped">
<caption>Displaying records 1 - 10</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 8%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">date</th>
<th style="text-align: left;">patient</th>
<th style="text-align: left;">encounter</th>
<th style="text-align: left;">category</th>
<th style="text-align: left;">code</th>
<th style="text-align: left;">description</th>
<th style="text-align: left;">value</th>
<th style="text-align: left;">units</th>
<th style="text-align: left;">type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1979-07-29 00:04:19</td>
<td style="text-align: left;">00e68a4d-4580-ac11-24fe-3a599d5ed94c</td>
<td style="text-align: left;">b36da282-8441-cc60-fa62-5d4a47bdf182</td>
<td style="text-align: left;">vital-signs</td>
<td style="text-align: left;">29463-7</td>
<td style="text-align: left;">Body Weight</td>
<td style="text-align: left;">99.4</td>
<td style="text-align: left;">kg</td>
<td style="text-align: left;">numeric</td>
</tr>
<tr class="even">
<td style="text-align: left;">1980-08-03 00:04:19</td>
<td style="text-align: left;">00e68a4d-4580-ac11-24fe-3a599d5ed94c</td>
<td style="text-align: left;">e68bc507-9d9a-1fc5-d833-33649e45e209</td>
<td style="text-align: left;">vital-signs</td>
<td style="text-align: left;">29463-7</td>
<td style="text-align: left;">Body Weight</td>
<td style="text-align: left;">98.2</td>
<td style="text-align: left;">kg</td>
<td style="text-align: left;">numeric</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2011-05-01 06:14:20</td>
<td style="text-align: left;">00e81bf7-89f5-8c22-b59a-dd6130421e7f</td>
<td style="text-align: left;">93b2e590-e180-820d-6dae-26ecebbe6076</td>
<td style="text-align: left;">vital-signs</td>
<td style="text-align: left;">29463-7</td>
<td style="text-align: left;">Body Weight</td>
<td style="text-align: left;">92.8</td>
<td style="text-align: left;">kg</td>
<td style="text-align: left;">numeric</td>
</tr>
<tr class="even">
<td style="text-align: left;">2012-04-01 06:14:20</td>
<td style="text-align: left;">00e81bf7-89f5-8c22-b59a-dd6130421e7f</td>
<td style="text-align: left;">3ff8a150-f6a3-1f98-43ed-8f182937ee4f</td>
<td style="text-align: left;">vital-signs</td>
<td style="text-align: left;">29463-7</td>
<td style="text-align: left;">Body Weight</td>
<td style="text-align: left;">92.8</td>
<td style="text-align: left;">kg</td>
<td style="text-align: left;">numeric</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1997-07-09 05:16:21</td>
<td style="text-align: left;">018b9499-1681-2af0-daef-e5c79d2fbd99</td>
<td style="text-align: left;">c4a573a4-9315-580d-1644-30e9dc9be606</td>
<td style="text-align: left;">vital-signs</td>
<td style="text-align: left;">29463-7</td>
<td style="text-align: left;">Body Weight</td>
<td style="text-align: left;">97.7</td>
<td style="text-align: left;">kg</td>
<td style="text-align: left;">numeric</td>
</tr>
<tr class="even">
<td style="text-align: left;">1998-07-15 05:16:21</td>
<td style="text-align: left;">018b9499-1681-2af0-daef-e5c79d2fbd99</td>
<td style="text-align: left;">511c4053-d262-7f9e-9492-a20b7b5ede73</td>
<td style="text-align: left;">vital-signs</td>
<td style="text-align: left;">29463-7</td>
<td style="text-align: left;">Body Weight</td>
<td style="text-align: left;">97.7</td>
<td style="text-align: left;">kg</td>
<td style="text-align: left;">numeric</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2005-01-16 17:27:51</td>
<td style="text-align: left;">01c2cb8b-1efa-0395-3db8-f3081953fd91</td>
<td style="text-align: left;">db75a362-3d89-d525-8120-f2cb52673d5a</td>
<td style="text-align: left;">vital-signs</td>
<td style="text-align: left;">29463-7</td>
<td style="text-align: left;">Body Weight</td>
<td style="text-align: left;">82.2</td>
<td style="text-align: left;">kg</td>
<td style="text-align: left;">numeric</td>
</tr>
<tr class="even">
<td style="text-align: left;">2006-01-22 17:27:51</td>
<td style="text-align: left;">01c2cb8b-1efa-0395-3db8-f3081953fd91</td>
<td style="text-align: left;">a5bc76e2-8871-1f42-a543-7890b67bbc95</td>
<td style="text-align: left;">vital-signs</td>
<td style="text-align: left;">29463-7</td>
<td style="text-align: left;">Body Weight</td>
<td style="text-align: left;">82.2</td>
<td style="text-align: left;">kg</td>
<td style="text-align: left;">numeric</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2007-11-20 22:00:50</td>
<td style="text-align: left;">0238959d-29a5-dc75-c375-c9bae56565ed</td>
<td style="text-align: left;">07d27e1f-e02b-b44e-f041-745919d249b8</td>
<td style="text-align: left;">vital-signs</td>
<td style="text-align: left;">29463-7</td>
<td style="text-align: left;">Body Weight</td>
<td style="text-align: left;">75.8</td>
<td style="text-align: left;">kg</td>
<td style="text-align: left;">numeric</td>
</tr>
<tr class="even">
<td style="text-align: left;">2008-11-25 22:00:50</td>
<td style="text-align: left;">0238959d-29a5-dc75-c375-c9bae56565ed</td>
<td style="text-align: left;">20b674ce-4365-889b-8d77-b2803a716603</td>
<td style="text-align: left;">vital-signs</td>
<td style="text-align: left;">29463-7</td>
<td style="text-align: left;">Body Weight</td>
<td style="text-align: left;">75.8</td>
<td style="text-align: left;">kg</td>
<td style="text-align: left;">numeric</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- calculating weight change from first and last body weight observation per patient using LAG function --</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="op">*</span> <span class="kw">FROM</span> (</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> patient, <span class="fu">CAST</span>(<span class="fu">value</span> <span class="kw">AS</span> <span class="dt">NUMERIC</span>) <span class="op">-</span> <span class="fu">lag</span>(<span class="fu">CAST</span>(<span class="fu">value</span> <span class="kw">AS</span> <span class="dt">NUMERIC</span>)) <span class="kw">OVER</span> (<span class="kw">PARTITION</span> <span class="kw">BY</span> patient) <span class="kw">AS</span> weight_change_in_kg</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> patient_weights</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>) <span class="kw">AS</span> temp</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co">-- returning weight changes greater than 0.0 --</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> weight_change_in_kg <span class="kw">IS</span> <span class="kw">NOT</span> <span class="kw">NULL</span> <span class="kw">AND</span> weight_change_in_kg <span class="op">&gt;</span> <span class="st">'0.0'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table class="table table-sm table-striped">
<caption>Displaying records 1 - 10</caption>
<thead>
<tr class="header">
<th style="text-align: left;">patient</th>
<th style="text-align: right;">weight_change_in_kg</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">04cb68bf-31f8-e3b9-fbf3-fa35396be193</td>
<td style="text-align: right;">1.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">04e6f4a7-ed39-7e2e-5ff8-2a3882620681</td>
<td style="text-align: right;">0.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">060fe906-d43f-5495-d728-09e07c04e03a</td>
<td style="text-align: right;">3.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">067395b1-0006-07e1-4440-223e9db7c604</td>
<td style="text-align: right;">1.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">09a8a547-62d6-1d04-6f0a-94ed6b70faf9</td>
<td style="text-align: right;">1.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">0b2315c0-0d9d-6266-0779-cfb1e02b7970</td>
<td style="text-align: right;">2.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">0bef66ec-8076-7b86-bc6e-4b527f53e4ed</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">1229e2eb-ffb3-feae-5d8c-ada8fc4701ed</td>
<td style="text-align: right;">3.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1503f751-1bdc-d253-6937-80505ba9b771</td>
<td style="text-align: right;">1.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">15753623-b40e-3433-adc3-a5d80cc2aaff</td>
<td style="text-align: right;">2.9</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- returns total count of patients that experienced a weight change greater than 0.0kg --</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">count</span>(<span class="kw">distinct</span> patient) <span class="kw">as</span> patient_count_weight_change_in_kg <span class="kw">FROM</span> (</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> patient, <span class="fu">CAST</span>(<span class="fu">value</span> <span class="kw">AS</span> <span class="dt">NUMERIC</span>) <span class="op">-</span> <span class="fu">lag</span>(<span class="fu">CAST</span>(<span class="fu">value</span> <span class="kw">AS</span> <span class="dt">NUMERIC</span>)) <span class="kw">OVER</span> (<span class="kw">PARTITION</span> <span class="kw">BY</span> patient) <span class="kw">AS</span> weight_change_in_kg</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> patient_weights</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>) <span class="kw">AS</span> temp</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> weight_change_in_kg <span class="kw">IS</span> <span class="kw">NOT</span> <span class="kw">NULL</span> <span class="kw">AND</span> weight_change_in_kg <span class="op">&gt;</span> <span class="st">'0.0'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table class="table table-sm table-striped">
<caption>1 records</caption>
<thead>
<tr class="header">
<th style="text-align: right;">patient_count_weight_change_in_kg</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">222</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Of 847 distinct patients in the dataset, 222 patients have experienced body weight changes. Knowing body weight change in CHF patients may be an indicator of fluid accumulation leading to CHF symptom exacerbation, these 222 patients may be good candidates for a nutrition counseling referral.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- (modifying query above) returns patient count from last query and average body weight change among all CHF patients identified to have body weight measurements at their encounters --</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">count</span>(<span class="kw">distinct</span> encounters.encounterclass), encounters.encounterclass, <span class="fu">count</span>(<span class="kw">distinct</span> temp.patient) <span class="kw">as</span> patient_count_weight_change_in_kg, <span class="fu">AVG</span>(weight_change_in_kg) <span class="kw">as</span> avg_wt_change</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> (<span class="kw">SELECT</span> patient, <span class="fu">CAST</span>(<span class="fu">value</span> <span class="kw">AS</span> <span class="dt">NUMERIC</span>) <span class="op">-</span> <span class="fu">lag</span>(<span class="fu">CAST</span>(<span class="fu">value</span> <span class="kw">AS</span> <span class="dt">NUMERIC</span>)) <span class="kw">OVER</span> (<span class="kw">PARTITION</span> <span class="kw">BY</span> patient) <span class="kw">AS</span> weight_change_in_kg</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> patient_weights</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>) <span class="kw">AS</span> temp, CHF_patients</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="kw">INNER</span> <span class="kw">JOIN</span> encounters <span class="kw">on</span> CHF_patients.patient <span class="op">=</span> encounters.patient</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> weight_change_in_kg <span class="kw">IS</span> <span class="kw">NOT</span> <span class="kw">NULL</span> <span class="kw">AND</span> weight_change_in_kg <span class="op">&gt;</span> <span class="st">'0.0'</span> </span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> encounters.encounterclass</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table class="table table-sm table-striped">
<caption>6 records</caption>
<colgroup>
<col style="width: 8%">
<col style="width: 21%">
<col style="width: 49%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">count</th>
<th style="text-align: left;">encounterclass</th>
<th style="text-align: right;">patient_count_weight_change_in_kg</th>
<th style="text-align: right;">avg_wt_change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">ambulatory</td>
<td style="text-align: right;">222</td>
<td style="text-align: right;">2.368469</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">emergency</td>
<td style="text-align: right;">222</td>
<td style="text-align: right;">2.368469</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">inpatient</td>
<td style="text-align: right;">222</td>
<td style="text-align: right;">2.368469</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">outpatient</td>
<td style="text-align: right;">222</td>
<td style="text-align: right;">2.368469</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">urgentcare</td>
<td style="text-align: right;">222</td>
<td style="text-align: right;">2.368469</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">wellness</td>
<td style="text-align: right;">222</td>
<td style="text-align: right;">2.368469</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- (modifying query above) returns average body weight among all CHF patients identified to have body weight measurement observations at their encounters --</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">count</span>(<span class="kw">distinct</span> encounters.encounterclass), encounters.encounterclass,  <span class="fu">AVG</span>(<span class="fu">CAST</span>(patient_weights.<span class="fu">value</span> <span class="kw">as</span> <span class="dt">NUMERIC</span>)) <span class="kw">as</span> avg_wt</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> patient_weights, CHF_patients</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="kw">INNER</span> <span class="kw">JOIN</span> encounters <span class="kw">on</span> CHF_patients.patient <span class="op">=</span> encounters.patient</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> encounters.encounterclass</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table class="table table-sm table-striped">
<caption>6 records</caption>
<thead>
<tr class="header">
<th style="text-align: right;">count</th>
<th style="text-align: left;">encounterclass</th>
<th style="text-align: right;">avg_wt</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">ambulatory</td>
<td style="text-align: right;">83.51747</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">emergency</td>
<td style="text-align: right;">83.51747</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">inpatient</td>
<td style="text-align: right;">83.51747</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">outpatient</td>
<td style="text-align: right;">83.51747</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">urgentcare</td>
<td style="text-align: right;">83.51747</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">wellness</td>
<td style="text-align: right;">83.51747</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The average weight change between all visits for CHF patients is about 2.4kg or 5.3lbs for patients admitted to the ED and seen in an inpatient setting, outpatient setting, for a wellness visit, at urgent care, and/or ambulatory care. This body weight change indicates CHF symptom exacerbation and need for patient re-education, additional medication management, and gives us an idea of when a patient may seek medical attention. It is important to note that, according to the American Heart Association, a weight gain of 5 or more pounds within a week for CHF patients signifies disease exacerbation and progression which may lead to emergency hospital admission (American Heart Association, 2019). Inhibiting exacerbation through preventative medicine such as referring patients to a nutritionist will aid CHF patients in maintaining an adequate heart-healthy diet and avoiding fluid accumulation and unwanted weight gain. Sustaining proper dietary compliance with appropriate mineral (salt) and fluid consumption, CHF patients will be able to avoid body weight fluctuations that lead to fluid accumulation, symptom exacerbation, and hospital admission.</p>
</section>
<section id="chf-patient-demographics-and-behavior-trends-when-admitted-to-the-ed" class="level3">
<h3 class="anchored" data-anchor-id="chf-patient-demographics-and-behavior-trends-when-admitted-to-the-ed">CHF Patient Demographics and Behavior Trends When Admitted to the ED</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- CHF patient population CTE used above --</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co">-- Note: I decided to keep the initial CHF_patient CTE for the following queries instead of using the local temp table above, so I could keep my queries organized and thought process straight --</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> CHF_patients <span class="kw">AS</span> (</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> careplans </span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> careplans.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span> <span class="kw">OR</span> careplans.reasoncode <span class="op">=</span> <span class="st">'88805009'</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">UNION</span> </span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> conditions </span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> conditions.description <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  <span class="kw">UNION</span> </span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>   <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> notes</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> notes.note_text <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>, CHF_demographics <span class="kw">as</span> (</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a><span class="co">-- selecting specific demographic and lifestyle data from CHF_patients --</span></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="kw">distinct</span> patients.<span class="kw">id</span>, patients.race, patients.gender,</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a><span class="co">-- calculating patient age by subtracting current year (2020) from patient's date of birth --</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>DATE_PART(<span class="st">'year'</span>, age(<span class="st">'09-24-2020'</span>, patients.birthdate)) <span class="kw">as</span> age, observations.<span class="fu">value</span> <span class="kw">as</span> smoking_status</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> patients</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a><span class="co">-- matching patients from initial CHF patient cohort from patients table and observations table --</span></span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a> <span class="kw">LEFT</span> <span class="kw">JOIN</span> CHF_patients <span class="kw">on</span> patients.<span class="kw">id</span> <span class="op">=</span> CHF_patients.patient</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a> <span class="kw">LEFT</span> <span class="kw">JOIN</span> observations <span class="kw">on</span> patients.<span class="kw">id</span> <span class="op">=</span> observations.patient</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>  <span class="kw">WHERE</span> patients.birthdate <span class="kw">IS</span> <span class="kw">NOT</span> <span class="kw">NULL</span></span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>  <span class="co">-- extracts patient smoking status/lifetsyle behaviors --</span></span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>  <span class="kw">AND</span> observations.description <span class="kw">LIKE</span> <span class="st">'%smoking status%'</span></span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>  <span class="kw">GROUP</span> <span class="kw">BY</span> patients.<span class="kw">id</span>, patients.race, patients.gender, age, smoking_status</span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a><span class="co">-- CTE to extract CHF patient encounters --</span></span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a>, CHF_encounters <span class="kw">as</span> (</span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a>  <span class="kw">SELECT</span> <span class="kw">distinct</span>(CHF_patients.patient), encounters.description, encounters.encounterclass</span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a>  <span class="kw">FROM</span> CHF_patients</span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a>  <span class="kw">LEFT</span> <span class="kw">JOIN</span> encounters <span class="kw">on</span> encounters.patient <span class="op">=</span> CHF_patients.patient</span>
<span id="cb15-35"><a href="#cb15-35" aria-hidden="true" tabindex="-1"></a>  <span class="kw">WHERE</span> encounters.reasoncode <span class="op">=</span> <span class="st">'88805009'</span> <span class="kw">OR</span> encounters.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span> </span>
<span id="cb15-36"><a href="#cb15-36" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-37"><a href="#cb15-37" aria-hidden="true" tabindex="-1"></a><span class="co">-- returns demographic information (age, gender, race), patient counts for each unique demographic/behavior and encounter observation --</span></span>
<span id="cb15-38"><a href="#cb15-38" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">count</span>(<span class="kw">distinct</span> CHF_encounters.patient) <span class="kw">as</span> pt_count, CHF_demographics.age, CHF_demographics.race, CHF_demographics.gender, CHF_demographics.smoking_status, CHF_encounters.encounterclass</span>
<span id="cb15-39"><a href="#cb15-39" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> CHF_demographics</span>
<span id="cb15-40"><a href="#cb15-40" aria-hidden="true" tabindex="-1"></a><span class="kw">LEFT</span> <span class="kw">JOIN</span> CHF_encounters <span class="kw">on</span> CHF_demographics.<span class="kw">id</span> <span class="op">=</span> CHF_encounters.patient</span>
<span id="cb15-41"><a href="#cb15-41" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> CHF_encounters.encounterclass <span class="kw">LIKE</span> <span class="st">'%emergency%'</span> <span class="co">-- returns specifically ED visit patient information --</span></span>
<span id="cb15-42"><a href="#cb15-42" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> CHF_demographics.age, CHF_encounters.encounterclass, CHF_demographics.race, CHF_demographics.gender, CHF_demographics.smoking_status</span>
<span id="cb15-43"><a href="#cb15-43" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> pt_count <span class="kw">DESC</span> <span class="co">-- returns patient count for each category desc. to identify patient trends for most-frequent ED visits --</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table class="table table-sm table-striped">
<caption>Displaying records 1 - 10</caption>
<thead>
<tr class="header">
<th style="text-align: right;">pt_count</th>
<th style="text-align: right;">age</th>
<th style="text-align: left;">race</th>
<th style="text-align: left;">gender</th>
<th style="text-align: left;">smoking_status</th>
<th style="text-align: left;">encounterclass</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: right;">87</td>
<td style="text-align: left;">black</td>
<td style="text-align: left;">M</td>
<td style="text-align: left;">Former smoker</td>
<td style="text-align: left;">emergency</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">99</td>
<td style="text-align: left;">black</td>
<td style="text-align: left;">M</td>
<td style="text-align: left;">Never smoker</td>
<td style="text-align: left;">emergency</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: right;">87</td>
<td style="text-align: left;">black</td>
<td style="text-align: left;">M</td>
<td style="text-align: left;">Never smoker</td>
<td style="text-align: left;">emergency</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">87</td>
<td style="text-align: left;">black</td>
<td style="text-align: left;">F</td>
<td style="text-align: left;">Never smoker</td>
<td style="text-align: left;">emergency</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">87</td>
<td style="text-align: left;">white</td>
<td style="text-align: left;">M</td>
<td style="text-align: left;">Former smoker</td>
<td style="text-align: left;">emergency</td>
</tr>
<tr class="even">
<td style="text-align: right;">9</td>
<td style="text-align: right;">87</td>
<td style="text-align: left;">white</td>
<td style="text-align: left;">M</td>
<td style="text-align: left;">Never smoker</td>
<td style="text-align: left;">emergency</td>
</tr>
<tr class="odd">
<td style="text-align: right;">8</td>
<td style="text-align: right;">87</td>
<td style="text-align: left;">white</td>
<td style="text-align: left;">F</td>
<td style="text-align: left;">Never smoker</td>
<td style="text-align: left;">emergency</td>
</tr>
<tr class="even">
<td style="text-align: right;">7</td>
<td style="text-align: right;">84</td>
<td style="text-align: left;">black</td>
<td style="text-align: left;">M</td>
<td style="text-align: left;">Never smoker</td>
<td style="text-align: left;">emergency</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">84</td>
<td style="text-align: left;">black</td>
<td style="text-align: left;">M</td>
<td style="text-align: left;">Former smoker</td>
<td style="text-align: left;">emergency</td>
</tr>
<tr class="even">
<td style="text-align: right;">7</td>
<td style="text-align: right;">84</td>
<td style="text-align: left;">white</td>
<td style="text-align: left;">M</td>
<td style="text-align: left;">Never smoker</td>
<td style="text-align: left;">emergency</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- CHF patient population CTE used above --</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> CHF_patients <span class="kw">AS</span> (</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> careplans </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> careplans.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span> <span class="kw">OR</span> careplans.reasoncode <span class="op">=</span> <span class="st">'88805009'</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">UNION</span> </span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> conditions </span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> conditions.description <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="kw">UNION</span> </span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>   <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> notes</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> notes.note_text <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>, CHF_demographics <span class="kw">as</span> (</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a><span class="co">-- selecting specific demographic and lifestyle data from CHF_patients --</span></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="kw">distinct</span> patients.<span class="kw">id</span>, patients.race, patients.gender,</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a><span class="co">-- calculating patient age by subtracting current year (2020) from patient's date of birth --</span></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>DATE_PART(<span class="st">'year'</span>, age(<span class="st">'09-24-2020'</span>, patients.birthdate)) <span class="kw">as</span> age, observations.<span class="fu">value</span> <span class="kw">as</span> smoking_status</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> patients</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a><span class="co">-- matching patients from initial CHF patient cohort from patients table and observations table --</span></span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a> <span class="kw">INNER</span> <span class="kw">JOIN</span> CHF_patients <span class="kw">on</span> patients.<span class="kw">id</span> <span class="op">=</span> CHF_patients.patient</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a> <span class="kw">LEFT</span> <span class="kw">JOIN</span> observations <span class="kw">on</span> patients.<span class="kw">id</span> <span class="op">=</span> observations.patient</span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>  <span class="kw">WHERE</span> patients.birthdate <span class="kw">IS</span> <span class="kw">NOT</span> <span class="kw">NULL</span></span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>  <span class="co">-- extracts patient smoking status/lifetsyle behaviors --</span></span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>  <span class="kw">AND</span> observations.description <span class="kw">LIKE</span> <span class="st">'%smoking status%'</span></span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>  <span class="kw">GROUP</span> <span class="kw">BY</span> patients.<span class="kw">id</span>, patients.race, patients.gender, age, smoking_status</span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a><span class="co">-- returns count breakdown of female and male CHF observations from our cohort --</span></span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">count</span>(<span class="kw">distinct</span> CHF_patients.patient), CHF_demographics.gender</span>
<span id="cb16-31"><a href="#cb16-31" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> CHF_demographics, CHF_patients</span>
<span id="cb16-32"><a href="#cb16-32" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> CHF_demographics.gender</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table class="table table-sm table-striped">
<caption>2 records</caption>
<thead>
<tr class="header">
<th style="text-align: right;">count</th>
<th style="text-align: left;">gender</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">847</td>
<td style="text-align: left;">F</td>
</tr>
<tr class="even">
<td style="text-align: right;">847</td>
<td style="text-align: left;">M</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- CHF patient population CTE used above --</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> CHF_patients <span class="kw">AS</span> (</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> careplans </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> careplans.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span> <span class="kw">OR</span> careplans.reasoncode <span class="op">=</span> <span class="st">'88805009'</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">UNION</span> </span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> conditions </span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> conditions.description <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  <span class="kw">UNION</span> </span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>   <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> notes</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> notes.note_text <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>, CHF_demographics <span class="kw">as</span> (</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a><span class="co">-- selecting specific demographic and lifestyle data from CHF_patients --</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="kw">distinct</span> patients.<span class="kw">id</span>, patients.race, patients.gender,</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a><span class="co">-- calculating patient age by subtracting current year (2020) from patient's date of birth --</span></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>DATE_PART(<span class="st">'year'</span>, age(<span class="st">'09-24-2020'</span>, patients.birthdate)) <span class="kw">as</span> age, observations.<span class="fu">value</span> <span class="kw">as</span> smoking_status</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> patients</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a><span class="co">-- matching patients from initial CHF patient cohort from patients table and observations table --</span></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a> <span class="kw">INNER</span> <span class="kw">JOIN</span> CHF_patients <span class="kw">on</span> patients.<span class="kw">id</span> <span class="op">=</span> CHF_patients.patient</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a> <span class="kw">LEFT</span> <span class="kw">JOIN</span> observations <span class="kw">on</span> patients.<span class="kw">id</span> <span class="op">=</span> observations.patient</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>  <span class="kw">WHERE</span> patients.birthdate <span class="kw">IS</span> <span class="kw">NOT</span> <span class="kw">NULL</span></span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>  <span class="co">-- extracts patient smoking status/lifetsyle behaviors --</span></span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>  <span class="kw">AND</span> observations.description <span class="kw">LIKE</span> <span class="st">'%smoking status%'</span></span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>  <span class="kw">GROUP</span> <span class="kw">BY</span> patients.<span class="kw">id</span>, patients.race, patients.gender, age, smoking_status</span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a><span class="co">-- returns count of patients 50+ years of age --</span></span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">count</span>(<span class="kw">distinct</span> CHF_demographics.<span class="kw">id</span>) <span class="kw">as</span> pt_age_fifty_and_over</span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> CHF_demographics, CHF_patients</span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> CHF_demographics.age <span class="op">&gt;=</span> <span class="st">'50'</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table class="table table-sm table-striped">
<caption>1 records</caption>
<thead>
<tr class="header">
<th style="text-align: right;">pt_age_fifty_and_over</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">816</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- CHF patient population CTE used above --</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> CHF_patients <span class="kw">AS</span> (</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> careplans </span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> careplans.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span> <span class="kw">OR</span> careplans.reasoncode <span class="op">=</span> <span class="st">'88805009'</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">UNION</span> </span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> conditions </span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> conditions.description <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="kw">UNION</span> </span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>   <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> notes</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> notes.note_text <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>, CHF_demographics <span class="kw">as</span> (</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a><span class="co">-- selecting specific demographic and lifestyle data from CHF_patients --</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="kw">distinct</span> patients.<span class="kw">id</span>, patients.race, patients.gender,</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a><span class="co">-- calculating patient age by subtracting current year (2020) from patient's date of birth --</span></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>DATE_PART(<span class="st">'year'</span>, age(<span class="st">'09-24-2020'</span>, patients.birthdate)) <span class="kw">as</span> age, observations.<span class="fu">value</span> <span class="kw">as</span> smoking_status</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> patients</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a><span class="co">-- matching patients from initial CHF patient cohort from patients table and observations table --</span></span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a> <span class="kw">INNER</span> <span class="kw">JOIN</span> CHF_patients <span class="kw">on</span> patients.<span class="kw">id</span> <span class="op">=</span> CHF_patients.patient</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a> <span class="kw">LEFT</span> <span class="kw">JOIN</span> observations <span class="kw">on</span> patients.<span class="kw">id</span> <span class="op">=</span> observations.patient</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>  <span class="kw">WHERE</span> patients.birthdate <span class="kw">IS</span> <span class="kw">NOT</span> <span class="kw">NULL</span></span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>  <span class="co">-- extracts patient smoking status/lifetsyle behaviors --</span></span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>  <span class="kw">AND</span> observations.description <span class="kw">LIKE</span> <span class="st">'%smoking status%'</span></span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>  <span class="kw">GROUP</span> <span class="kw">BY</span> patients.<span class="kw">id</span>, patients.race, patients.gender, age, smoking_status</span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a><span class="co">-- returns count of patients less than 50 years of age --</span></span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">count</span>(<span class="kw">distinct</span> CHF_demographics.<span class="kw">id</span>) <span class="kw">as</span> pt_age_under_fifty</span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> CHF_demographics, CHF_patients</span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> CHF_demographics.age <span class="op">&lt;</span> <span class="st">'50'</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table class="table table-sm table-striped">
<caption>1 records</caption>
<thead>
<tr class="header">
<th style="text-align: right;">pt_age_under_fifty</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">31</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- CHF patient population CTE used above --</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> CHF_patients <span class="kw">AS</span> (</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> careplans </span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> careplans.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span> <span class="kw">OR</span> careplans.reasoncode <span class="op">=</span> <span class="st">'88805009'</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">UNION</span> </span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> conditions </span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> conditions.description <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="kw">UNION</span> </span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>   <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> notes</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> notes.note_text <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>, CHF_demographics <span class="kw">as</span> (</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a><span class="co">-- selecting specific demographic and lifestyle data from CHF_patients --</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="kw">distinct</span> patients.<span class="kw">id</span>, patients.race, patients.gender,</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a><span class="co">-- calculating patient age by subtracting current year (2020) from patient's date of birth --</span></span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>DATE_PART(<span class="st">'year'</span>, age(<span class="st">'09-24-2020'</span>, patients.birthdate)) <span class="kw">as</span> age, observations.<span class="fu">value</span> <span class="kw">as</span> smoking_status</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> patients</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a><span class="co">-- matching patients from initial CHF patient cohort from patients table and observations table --</span></span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a> <span class="kw">INNER</span> <span class="kw">JOIN</span> CHF_patients <span class="kw">on</span> patients.<span class="kw">id</span> <span class="op">=</span> CHF_patients.patient</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a> <span class="kw">LEFT</span> <span class="kw">JOIN</span> observations <span class="kw">on</span> patients.<span class="kw">id</span> <span class="op">=</span> observations.patient</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>  <span class="kw">WHERE</span> patients.birthdate <span class="kw">IS</span> <span class="kw">NOT</span> <span class="kw">NULL</span></span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>  <span class="co">-- extracts patient smoking status/lifetsyle behaviors --</span></span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>  <span class="kw">AND</span> observations.description <span class="kw">LIKE</span> <span class="st">'%smoking status%'</span></span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>  <span class="kw">GROUP</span> <span class="kw">BY</span> patients.<span class="kw">id</span>, patients.race, patients.gender, age, smoking_status</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a><span class="co">-- returns count of patients 65+ years of age --</span></span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">count</span>(<span class="kw">distinct</span> CHF_demographics.<span class="kw">id</span>) <span class="kw">as</span> pt_age_eligible_for_medicare</span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> CHF_demographics, CHF_patients</span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> CHF_demographics.age <span class="op">&gt;=</span> <span class="st">'65'</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table class="table table-sm table-striped">
<caption>1 records</caption>
<thead>
<tr class="header">
<th style="text-align: right;">pt_age_eligible_for_medicare</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">706</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- CHF patient population CTE used above --</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> CHF_patients <span class="kw">AS</span> (</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> careplans </span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> careplans.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span> <span class="kw">OR</span> careplans.reasoncode <span class="op">=</span> <span class="st">'88805009'</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">UNION</span> </span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> conditions </span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> conditions.description <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="kw">UNION</span> </span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>   <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> notes</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> notes.note_text <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>, CHF_demographics <span class="kw">as</span> (</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a><span class="co">-- selecting specific demographic and lifestyle data from CHF_patients --</span></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="kw">distinct</span> patients.<span class="kw">id</span>, patients.race, patients.gender,</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a><span class="co">-- calculating patient age by subtracting current year (2020) from patient's date of birth --</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>DATE_PART(<span class="st">'year'</span>, age(<span class="st">'09-24-2020'</span>, patients.birthdate)) <span class="kw">as</span> age, observations.<span class="fu">value</span> <span class="kw">as</span> smoking_status</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> patients</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a><span class="co">-- matching patients from initial CHF patient cohort from patients table and observations table --</span></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a> <span class="kw">INNER</span> <span class="kw">JOIN</span> CHF_patients <span class="kw">on</span> patients.<span class="kw">id</span> <span class="op">=</span> CHF_patients.patient</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a> <span class="kw">LEFT</span> <span class="kw">JOIN</span> observations <span class="kw">on</span> patients.<span class="kw">id</span> <span class="op">=</span> observations.patient</span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>  <span class="kw">WHERE</span> patients.birthdate <span class="kw">IS</span> <span class="kw">NOT</span> <span class="kw">NULL</span></span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>  <span class="co">-- extracts patient smoking status/lifetsyle behaviors --</span></span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>  <span class="kw">AND</span> observations.description <span class="kw">LIKE</span> <span class="st">'%smoking status%'</span></span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>  <span class="kw">GROUP</span> <span class="kw">BY</span> patients.<span class="kw">id</span>, patients.race, patients.gender, age, smoking_status</span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a><span class="co">-- returns average patient age for CHF cohort --</span></span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">AVG</span>(<span class="fu">CAST</span>(CHF_demographics.age <span class="kw">as</span> <span class="dt">NUMERIC</span>)) <span class="kw">as</span> avg_pt_age, CHF_demographics.gender</span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> CHF_demographics</span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> CHF_demographics.gender</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table class="table table-sm table-striped">
<caption>2 records</caption>
<thead>
<tr class="header">
<th style="text-align: right;">avg_pt_age</th>
<th style="text-align: left;">gender</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">82.88482</td>
<td style="text-align: left;">F</td>
</tr>
<tr class="even">
<td style="text-align: right;">81.36211</td>
<td style="text-align: left;">M</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- CHF patient population CTE used above --</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> CHF_patients <span class="kw">AS</span> (</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> careplans </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> careplans.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span> <span class="kw">OR</span> careplans.reasoncode <span class="op">=</span> <span class="st">'88805009'</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">UNION</span> </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> conditions </span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> conditions.description <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="kw">UNION</span> </span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>   <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> notes</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> notes.note_text <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>, CHF_demographics <span class="kw">as</span> (</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a><span class="co">-- selecting specific demographic and lifestyle data from CHF_patients --</span></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="kw">distinct</span> patients.<span class="kw">id</span>, patients.race, patients.gender,</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a><span class="co">-- calculating patient age by subtracting current year (2020) from patient's date of birth --</span></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>DATE_PART(<span class="st">'year'</span>, age(<span class="st">'09-24-2020'</span>, patients.birthdate)) <span class="kw">as</span> age, observations.<span class="fu">value</span> <span class="kw">as</span> smoking_status</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> patients</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a><span class="co">-- matching patients from initial CHF patient cohort from patients table and observations table --</span></span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a> <span class="kw">INNER</span> <span class="kw">JOIN</span> CHF_patients <span class="kw">on</span> patients.<span class="kw">id</span> <span class="op">=</span> CHF_patients.patient</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a> <span class="kw">LEFT</span> <span class="kw">JOIN</span> observations <span class="kw">on</span> patients.<span class="kw">id</span> <span class="op">=</span> observations.patient</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>  <span class="kw">WHERE</span> patients.birthdate <span class="kw">IS</span> <span class="kw">NOT</span> <span class="kw">NULL</span></span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>  <span class="co">-- extracts patient smoking status/lifetsyle behaviors --</span></span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>  <span class="kw">AND</span> observations.description <span class="kw">LIKE</span> <span class="st">'%smoking status%'</span></span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>  <span class="kw">GROUP</span> <span class="kw">BY</span> patients.<span class="kw">id</span>, patients.race, patients.gender, age, smoking_status</span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a><span class="co">-- returns count of patients over 50 years of age --</span></span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">count</span>(<span class="kw">distinct</span> CHF_demographics.<span class="kw">id</span>) <span class="kw">as</span> pt_count, CHF_demographics.smoking_status</span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> CHF_demographics</span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> CHF_demographics.smoking_status</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table class="table table-sm table-striped">
<caption>3 records</caption>
<thead>
<tr class="header">
<th style="text-align: right;">pt_count</th>
<th style="text-align: left;">smoking_status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: left;">Current every day smoker</td>
</tr>
<tr class="even">
<td style="text-align: right;">345</td>
<td style="text-align: left;">Former smoker</td>
</tr>
<tr class="odd">
<td style="text-align: right;">505</td>
<td style="text-align: left;">Never smoker</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- CHF patient population CTE used above --</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> CHF_patients <span class="kw">AS</span> (</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> careplans </span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> careplans.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span> <span class="kw">OR</span> careplans.reasoncode <span class="op">=</span> <span class="st">'88805009'</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">UNION</span> </span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> conditions </span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> conditions.description <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>  <span class="kw">UNION</span> </span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>   <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> notes</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> notes.note_text <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>, CHF_demographics <span class="kw">as</span> (</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a><span class="co">-- selecting specific demographic and lifestyle data from CHF_patients --</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="kw">distinct</span> patients.<span class="kw">id</span>, patients.race, patients.gender,</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a><span class="co">-- calculating patient age by subtracting current year (2020) from patient's date of birth --</span></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>DATE_PART(<span class="st">'year'</span>, age(<span class="st">'09-24-2020'</span>, patients.birthdate)) <span class="kw">as</span> age, observations.<span class="fu">value</span> <span class="kw">as</span> smoking_status</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> patients</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a><span class="co">-- matching patients from initial CHF patient cohort from patients table and observations table --</span></span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a> <span class="kw">INNER</span> <span class="kw">JOIN</span> CHF_patients <span class="kw">on</span> patients.<span class="kw">id</span> <span class="op">=</span> CHF_patients.patient</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a> <span class="kw">LEFT</span> <span class="kw">JOIN</span> observations <span class="kw">on</span> patients.<span class="kw">id</span> <span class="op">=</span> observations.patient</span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>  <span class="kw">WHERE</span> patients.birthdate <span class="kw">IS</span> <span class="kw">NOT</span> <span class="kw">NULL</span></span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>  <span class="co">-- extracts patient smoking status/lifetsyle behaviors --</span></span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>  <span class="kw">AND</span> observations.description <span class="kw">LIKE</span> <span class="st">'%smoking status%'</span></span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a>  <span class="kw">GROUP</span> <span class="kw">BY</span> patients.<span class="kw">id</span>, patients.race, patients.gender, age, smoking_status</span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a><span class="co">-- returns count of patients over 50 years of age --</span></span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">count</span>(<span class="kw">distinct</span> CHF_demographics.<span class="kw">id</span>), CHF_demographics.race</span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> CHF_demographics</span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> CHF_demographics.race</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table class="table table-sm table-striped">
<caption>6 records</caption>
<thead>
<tr class="header">
<th style="text-align: right;">count</th>
<th style="text-align: left;">race</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">23</td>
<td style="text-align: left;">asian</td>
</tr>
<tr class="even">
<td style="text-align: right;">433</td>
<td style="text-align: left;">black</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: left;">hawaiian</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: left;">native</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13</td>
<td style="text-align: left;">other</td>
</tr>
<tr class="even">
<td style="text-align: right;">361</td>
<td style="text-align: left;">white</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The tables above returns the demographic and smoking status of CHF patients in the Synthea dataset. From this data, we can gauge common demographic and lifestyle trends in CHF patient ED admissions. In general, the count of patients who have been seen in the ED begin to rise as age increases. Of our 847 patients, 31 patients are younger than 50 years old and 816 are 50+ years of age. It is also interesting to note, 706 patients are 65+ years old - the initial age to enroll in Medicare. This may be important when analyzing CHF patient-associated expenditure as we already know hospital readmission within 30 days are not reimbursed and Medicare rates are fixed and reimbursement rates are lower than private insurance. Additionally, Medicare patients tend to be more expensive as they include an older population at higher risk for chronic illness and frequent medical care visits (American Hospital Association, 2020). This information is significant in highlighting a need to explore areas for quality improvement in CHF patient care.</p>
<p>The average age of CHF patients is 82 years old for Females and 81 years old for Males. Looking at patient lifestyle behaviors, 7 CHF patients are current smokers, 345 are former smokers, and 505 have never smoked. Grouping CHF patients by race, we identified African American/black and white patients have the highest incidence of CHF diagnosis. There was no significant difference between number of females verses males diagnosed with CHF. Identifying areas where there are high patient counts (pt_count) could aid our hospital organization in pin-pointing patients at greater risk for CHF symptom exacerbation and possible ED admission early on in the care management process.</p>
</section>
<section id="chf-patient-visit-breakdown" class="level3">
<h3 class="anchored" data-anchor-id="chf-patient-visit-breakdown">CHF Patient Visit Breakdown</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- CHF patient population CTE used above --</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> CHF_patients <span class="kw">AS</span> (</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> careplans </span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> careplans.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span> <span class="kw">OR</span> careplans.reasoncode <span class="op">=</span> <span class="st">'88805009'</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">UNION</span> </span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> conditions </span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> conditions.description <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  <span class="kw">UNION</span> </span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>   <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> notes</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> notes.note_text <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a><span class="co">-- CTE to extract CHF patient encounters --</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>, CHF_encounters <span class="kw">as</span> (</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>  <span class="kw">SELECT</span> <span class="kw">distinct</span>(CHF_patients.patient), encounters.description, encounters.encounterclass, encounters.<span class="kw">start</span></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>  <span class="kw">FROM</span> CHF_patients</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>  <span class="kw">LEFT</span> <span class="kw">JOIN</span> encounters <span class="kw">on</span> encounters.patient <span class="op">=</span> CHF_patients.patient</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>  <span class="kw">WHERE</span> encounters.reasoncode <span class="op">=</span> <span class="st">'88805009'</span> <span class="kw">OR</span> encounters.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span> </span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">count</span>(<span class="kw">distinct</span> CHF_encounters.patient) <span class="kw">as</span> CHF_patient_count, CHF_encounters.description, CHF_encounters.encounterclass</span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> CHF_encounters</span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a><span class="co">-- returns CHF patient visits within the past 12mo --</span></span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> (CHF_encounters.<span class="kw">start</span> <span class="op">&lt;=</span> <span class="st">'09-24-2020'</span> <span class="kw">AND</span> CHF_encounters.<span class="kw">start</span> <span class="op">&gt;=</span> <span class="st">'09-24-2019'</span>)</span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> CHF_encounters.description, CHF_encounters.encounterclass</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table class="table table-sm table-striped">
<caption>5 records</caption>
<colgroup>
<col style="width: 23%">
<col style="width: 57%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">chf_patient_count</th>
<th style="text-align: left;">description</th>
<th style="text-align: left;">encounterclass</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">46</td>
<td style="text-align: left;">Admission to intensive care unit (procedure)</td>
<td style="text-align: left;">inpatient</td>
</tr>
<tr class="even">
<td style="text-align: right;">23</td>
<td style="text-align: left;">Death Certification</td>
<td style="text-align: left;">wellness</td>
</tr>
<tr class="odd">
<td style="text-align: right;">88</td>
<td style="text-align: left;">Encounter for problem</td>
<td style="text-align: left;">ambulatory</td>
</tr>
<tr class="even">
<td style="text-align: right;">46</td>
<td style="text-align: left;">Encounter for Problem</td>
<td style="text-align: left;">emergency</td>
</tr>
<tr class="odd">
<td style="text-align: right;">37</td>
<td style="text-align: left;">Telemedicine consultation with patient</td>
<td style="text-align: left;">ambulatory</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- CHF patient population CTE used above --</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> CHF_patients <span class="kw">AS</span> (</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> careplans </span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> careplans.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span> <span class="kw">OR</span> careplans.reasoncode <span class="op">=</span> <span class="st">'88805009'</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">UNION</span> </span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> conditions </span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> conditions.description <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="kw">UNION</span> </span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>   <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> notes</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> notes.note_text <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a><span class="co">-- CTE to extract CHF patient encounters --</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>, CHF_encounters <span class="kw">as</span> (</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>  <span class="kw">SELECT</span> <span class="kw">distinct</span>(CHF_patients.patient), encounters.description, encounters.encounterclass</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>  <span class="kw">FROM</span> CHF_patients</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>  <span class="kw">LEFT</span> <span class="kw">JOIN</span> encounters <span class="kw">on</span> encounters.patient <span class="op">=</span> CHF_patients.patient</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>  <span class="kw">WHERE</span> encounters.reasoncode <span class="op">=</span> <span class="st">'88805009'</span> <span class="kw">OR</span> encounters.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">count</span>(<span class="kw">distinct</span> CHF_encounters.patient) <span class="kw">as</span> CHF_patient_count, CHF_encounters.description, CHF_encounters.encounterclass</span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> CHF_encounters</span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> CHF_encounters.description, CHF_encounters.encounterclass</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table class="table table-sm table-striped">
<caption>7 records</caption>
<colgroup>
<col style="width: 23%">
<col style="width: 57%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">chf_patient_count</th>
<th style="text-align: left;">description</th>
<th style="text-align: left;">encounterclass</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: left;">Admission to hospice (procedure)</td>
<td style="text-align: left;">ambulatory</td>
</tr>
<tr class="even">
<td style="text-align: right;">774</td>
<td style="text-align: left;">Admission to intensive care unit (procedure)</td>
<td style="text-align: left;">inpatient</td>
</tr>
<tr class="odd">
<td style="text-align: right;">708</td>
<td style="text-align: left;">Death Certification</td>
<td style="text-align: left;">wellness</td>
</tr>
<tr class="even">
<td style="text-align: right;">847</td>
<td style="text-align: left;">Encounter for problem</td>
<td style="text-align: left;">ambulatory</td>
</tr>
<tr class="odd">
<td style="text-align: right;">774</td>
<td style="text-align: left;">Encounter for Problem</td>
<td style="text-align: left;">emergency</td>
</tr>
<tr class="even">
<td style="text-align: right;">7</td>
<td style="text-align: left;">Surgical procedure (procedure)</td>
<td style="text-align: left;">inpatient</td>
</tr>
<tr class="odd">
<td style="text-align: right;">305</td>
<td style="text-align: left;">Telemedicine consultation with patient</td>
<td style="text-align: left;">ambulatory</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Over the last 12 months, there have been a total of 46 patients admitted to the ED. There have been 774 total CHF patients seen in the ED for visits in the Synthea dataset. It is important to note the patient count for both emergency visits and inpatient admission to the Intensive Care Unit (ICU) are the same for our CHF cohort. This could provide evidence of serious symptom exacerbation for CHF patients (leading to the need for intensive care and additional usage of hospital resources) and provide reason for necessary intervention in order to improve patient health management.</p>
</section>
<section id="chf-patient-common-medications" class="level3">
<h3 class="anchored" data-anchor-id="chf-patient-common-medications">CHF Patient Common Medications</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- CHF patient population CTE used above --</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> CHF_patients <span class="kw">AS</span> (</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> careplans </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> careplans.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span> <span class="kw">OR</span> careplans.reasoncode <span class="op">=</span> <span class="st">'88805009'</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">UNION</span> </span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> conditions </span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> conditions.description <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>  <span class="kw">UNION</span> </span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>   <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> notes</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> notes.note_text <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a><span class="co">-- CTE to extract CHF patient encounters --</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>, CHF_encounters <span class="kw">as</span> (</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>  <span class="kw">SELECT</span> <span class="kw">distinct</span>(CHF_patients.patient), encounters.description, encounters.encounterclass</span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>  <span class="kw">FROM</span> CHF_patients</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>  <span class="kw">LEFT</span> <span class="kw">JOIN</span> encounters <span class="kw">on</span> encounters.patient <span class="op">=</span> CHF_patients.patient</span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>  <span class="kw">WHERE</span> encounters.reasoncode <span class="op">=</span> <span class="st">'88805009'</span> <span class="kw">OR</span> encounters.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a><span class="co">-- CTE to extract specific medications used to treat our CHF patient cohort --</span></span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>, CHF_medications <span class="kw">as</span> (</span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>  <span class="kw">SELECT</span> <span class="kw">distinct</span>(CHF_patients.patient), medications.description, medications.reasondescription</span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>  <span class="kw">FROM</span> CHF_patients</span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a>  <span class="kw">LEFT</span> <span class="kw">JOIN</span> medications <span class="kw">on</span> CHF_patients.patient <span class="op">=</span> medications.patient</span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>  <span class="kw">WHERE</span> medications.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a><span class="co">-- returns encounter and medication information for CHF patient cohort --</span></span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">count</span>(<span class="kw">distinct</span> CHF_encounters.patient) <span class="kw">as</span> CHF_patient_encounter_count, CHF_encounters.description, CHF_encounters.encounterclass, <span class="fu">count</span>(<span class="kw">distinct</span> CHF_medications.patient) <span class="kw">as</span> CHF_patient_med_count, CHF_medications.description, CHF_medications.reasondescription</span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> CHF_encounters, CHF_medications</span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> CHF_encounters.encounterclass <span class="kw">LIKE</span> <span class="st">'%emergency'</span></span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> CHF_encounters.description, CHF_encounters.encounterclass, CHF_medications.description, CHF_medications.reasondescription</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table class="table table-sm table-striped">
<caption>6 records</caption>
<colgroup>
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 26%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">chf_patient_encounter_count</th>
<th style="text-align: left;">description</th>
<th style="text-align: left;">encounterclass</th>
<th style="text-align: right;">chf_patient_med_count</th>
<th style="text-align: left;">description..5</th>
<th style="text-align: left;">reasondescription</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">774</td>
<td style="text-align: left;">Encounter for Problem</td>
<td style="text-align: left;">emergency</td>
<td style="text-align: right;">774</td>
<td style="text-align: left;">10 ML Furosemide 10 MG/ML Injection</td>
<td style="text-align: left;">Chronic congestive heart failure (disorder)</td>
</tr>
<tr class="even">
<td style="text-align: right;">774</td>
<td style="text-align: left;">Encounter for Problem</td>
<td style="text-align: left;">emergency</td>
<td style="text-align: right;">435</td>
<td style="text-align: left;">carvedilol 25 MG Oral Tablet</td>
<td style="text-align: left;">Chronic congestive heart failure (disorder)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">774</td>
<td style="text-align: left;">Encounter for Problem</td>
<td style="text-align: left;">emergency</td>
<td style="text-align: right;">842</td>
<td style="text-align: left;">Furosemide 40 MG Oral Tablet</td>
<td style="text-align: left;">Chronic congestive heart failure (disorder)</td>
</tr>
<tr class="even">
<td style="text-align: right;">774</td>
<td style="text-align: left;">Encounter for Problem</td>
<td style="text-align: left;">emergency</td>
<td style="text-align: right;">344</td>
<td style="text-align: left;">lisinopril 20 MG Oral Tablet</td>
<td style="text-align: left;">Chronic congestive heart failure (disorder)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">774</td>
<td style="text-align: left;">Encounter for Problem</td>
<td style="text-align: left;">emergency</td>
<td style="text-align: right;">356</td>
<td style="text-align: left;">losartan potassium 50 MG Oral Tablet</td>
<td style="text-align: left;">Chronic congestive heart failure (disorder)</td>
</tr>
<tr class="even">
<td style="text-align: right;">774</td>
<td style="text-align: left;">Encounter for Problem</td>
<td style="text-align: left;">emergency</td>
<td style="text-align: right;">124</td>
<td style="text-align: left;">sacubitril 97 MG / valsartan 103 MG Oral Tablet</td>
<td style="text-align: left;">Chronic congestive heart failure (disorder)</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The query above explores the common medications associated with CHF patient admission to the ED. It is important to note that the medication with the highest patient count, Furosemide, is a common diuretic medication used to treat excess fluid retention in patients. Observing a high patient count for a diuretic medication supports what we have gleaned from our data above noting a high incidence of CHF patient weight fluctuation, weight gain, and emergency hospital admission. An intervention incorporated within standard of care focused on preventing fluid accumulation such as nutritionist counseling appointment may assist with preventing inadequately managed disease in CHF patients.</p>
</section>
<section id="serum-sodium-control" class="level3">
<h3 class="anchored" data-anchor-id="serum-sodium-control">Serum Sodium Control</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- CTE to extract CHF patient encounters --</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> CHF_encounters <span class="kw">as</span> (</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="kw">SELECT</span> <span class="kw">distinct</span>(CHF_patients.patient), encounters.description, encounters.encounterclass</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="kw">FROM</span> CHF_patients</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="kw">LEFT</span> <span class="kw">JOIN</span> encounters <span class="kw">on</span> encounters.patient <span class="op">=</span> CHF_patients.patient</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="kw">WHERE</span> encounters.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span> <span class="kw">and</span> encounters.encounterclass <span class="kw">LIKE</span> <span class="st">'%emergency'</span> </span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="co">-- CTE to hold CHF patient sodium observations for patient encounters -- </span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>, CHF_observations <span class="kw">as</span> (</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  <span class="kw">SELECT</span> <span class="kw">distinct</span>(CHF_encounters.patient), observations.<span class="fu">value</span>, observations.description</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>  <span class="kw">FROM</span> CHF_encounters</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>  <span class="kw">LEFT</span> <span class="kw">JOIN</span> observations <span class="kw">on</span> CHF_encounters.patient <span class="op">=</span> observations.patient</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>  <span class="co">-- returns abnormal/out-of-range serum sodium observations for CHF patients --</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>  <span class="kw">WHERE</span> observations.description <span class="kw">LIKE</span> <span class="st">'%Sodium%'</span> <span class="kw">AND</span> (observations.<span class="fu">value</span> <span class="op">&lt;</span> <span class="st">'135.0'</span> <span class="kw">OR</span> observations.<span class="fu">value</span> <span class="op">&gt;</span> <span class="st">'145.0'</span>) <span class="co">-- no observations recorded out of range --</span></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">count</span>(<span class="kw">distinct</span> CHF_encounters.patient) <span class="kw">as</span> CHF_patient_encounter_count, CHF_encounters.description, CHF_encounters.encounterclass, <span class="fu">count</span>(<span class="kw">distinct</span> CHF_observations.patient) <span class="kw">as</span> CHF_observ_count, CHF_observations.description, CHF_observations.<span class="fu">value</span></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> CHF_encounters, CHF_observations</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a><span class="kw">GROUP</span> <span class="kw">BY</span> CHF_encounters.description, CHF_encounters.encounterclass, CHF_observations.description, CHF_observations.<span class="fu">value</span></span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a><span class="co">--ORDER BY CHF_observations.value DESC</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table>
<caption>0 records</caption>
<colgroup>
<col style="width: 30%">
<col style="width: 12%">
<col style="width: 16%">
<col style="width: 18%">
<col style="width: 16%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">chf_patient_encounter_count</th>
<th style="text-align: left;">description</th>
<th style="text-align: left;">encounterclass</th>
<th style="text-align: right;">chf_observ_count</th>
<th style="text-align: left;">description..5</th>
<th style="text-align: left;">value</th>
</tr>
</thead>
<tbody>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- CTE to extract CHF patient encounters --</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> CHF_encounters <span class="kw">as</span> (</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="kw">SELECT</span> <span class="kw">distinct</span>(CHF_patients.patient), encounters.description, encounters.encounterclass</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="kw">FROM</span> CHF_patients</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="kw">LEFT</span> <span class="kw">JOIN</span> encounters <span class="kw">on</span> encounters.patient <span class="op">=</span> CHF_patients.patient</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="kw">WHERE</span> encounters.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span> <span class="kw">and</span> encounters.encounterclass <span class="kw">LIKE</span> <span class="st">'%emergency'</span> </span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="co">-- CTE to hold CHF patient sodium observations for patient encounters -- </span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>, CHF_observations <span class="kw">as</span> (</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>  <span class="kw">SELECT</span> <span class="kw">distinct</span>(CHF_encounters.patient), observations.<span class="fu">value</span>, observations.description</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>  <span class="kw">FROM</span> CHF_encounters</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>  <span class="kw">LEFT</span> <span class="kw">JOIN</span> observations <span class="kw">on</span> CHF_encounters.patient <span class="op">=</span> observations.patient</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>  <span class="kw">WHERE</span> observations.description <span class="kw">LIKE</span> <span class="st">'%Sodium%'</span> </span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a><span class="co">-- returns average sodium level for CHF cohort --</span></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">AVG</span>(<span class="fu">CAST</span>(CHF_observations.<span class="fu">value</span> <span class="kw">as</span> <span class="dt">NUMERIC</span>)) <span class="kw">as</span> avg_sodium </span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> CHF_observations</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table class="table table-sm table-striped">
<caption>1 records</caption>
<thead>
<tr class="header">
<th style="text-align: right;">avg_sodium</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">140.0405</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Serum sodium levels is also an indicator of managed or unmanaged disease. There are no CHF patients that have been admitted to the ED that have had abnormal serum sodium levels observed. Average sodium level for CHF patients is within target range (135-145mEq/dL) at 140mEq/dL.</p>
</section>
<section id="blood-pressure-control" class="level3">
<h3 class="anchored" data-anchor-id="blood-pressure-control">Blood Pressure Control</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- CHF patient population CTE used above --</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> CHF_patients <span class="kw">AS</span> (</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> careplans </span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> careplans.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span> <span class="kw">OR</span> careplans.reasoncode <span class="op">=</span> <span class="st">'88805009'</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">UNION</span> </span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> conditions </span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> conditions.description <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="kw">UNION</span> </span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>   <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> notes</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> notes.note_text <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a><span class="co">-- CTE to extract CHF patient encounters --</span></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>, CHF_encounters <span class="kw">as</span> (</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>  <span class="kw">SELECT</span> <span class="kw">distinct</span>(CHF_patients.patient), encounters.description, encounters.encounterclass</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>  <span class="kw">FROM</span> CHF_patients</span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>  <span class="kw">LEFT</span> <span class="kw">JOIN</span> encounters <span class="kw">on</span> encounters.patient <span class="op">=</span> CHF_patients.patient</span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>  <span class="kw">WHERE</span> encounters.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a><span class="co">-- CTE to hold CHF patient blood pressure (BP) observations where BP is abnormal/out-of-range --</span></span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a>, CHF_bp <span class="kw">as</span> (</span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> CHF_encounters.patient, observations.<span class="fu">value</span>, observations.description</span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a>  <span class="kw">FROM</span> CHF_encounters</span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a>  <span class="kw">LEFT</span> <span class="kw">JOIN</span> observations <span class="kw">on</span> CHF_encounters.patient <span class="op">=</span> observations.patient</span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a>  <span class="kw">WHERE</span> (observations.description <span class="kw">LIKE</span> <span class="st">'%Systolic Blood Pressure%'</span> <span class="kw">AND</span> observations.<span class="fu">value</span> <span class="op">&gt;</span> <span class="st">'130.0'</span>) <span class="kw">OR</span> (observations.description <span class="kw">LIKE</span> <span class="st">'%Systolic Blood Pressure%'</span> <span class="kw">AND</span> observations.<span class="fu">value</span> <span class="op">&lt;</span> <span class="st">'110.0'</span>) <span class="kw">OR</span> (observations.description <span class="kw">LIKE</span> <span class="st">'%Diastolic Blood Pressure%'</span> <span class="kw">AND</span> observations.<span class="fu">value</span> <span class="op">&gt;=</span> <span class="st">'90.0'</span>)</span>
<span id="cb28-28"><a href="#cb28-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb28-29"><a href="#cb28-29" aria-hidden="true" tabindex="-1"></a><span class="co">-- returns count of patients where bp is observed to be abnormal/out-of-range</span></span>
<span id="cb28-30"><a href="#cb28-30" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">count</span>(<span class="kw">distinct</span> CHF_bp.patient) <span class="kw">as</span> unmanaged_bp_pts</span>
<span id="cb28-31"><a href="#cb28-31" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> CHF_bp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table class="table table-sm table-striped">
<caption>1 records</caption>
<thead>
<tr class="header">
<th style="text-align: right;">unmanaged_bp_pts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">791</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- CHF patient population CTE used above --</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> CHF_patients <span class="kw">AS</span> (</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> careplans </span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> careplans.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span> <span class="kw">OR</span> careplans.reasoncode <span class="op">=</span> <span class="st">'88805009'</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">UNION</span> </span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> conditions </span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> conditions.description <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>  <span class="kw">UNION</span> </span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>   <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> notes</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> notes.note_text <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a><span class="co">-- CTE to extract CHF patient encounters --</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>, CHF_encounters <span class="kw">as</span> (</span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>  <span class="kw">SELECT</span> <span class="kw">distinct</span>(CHF_patients.patient), encounters.description, encounters.encounterclass</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>  <span class="kw">FROM</span> CHF_patients</span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>  <span class="kw">LEFT</span> <span class="kw">JOIN</span> encounters <span class="kw">on</span> encounters.patient <span class="op">=</span> CHF_patients.patient</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>  <span class="kw">WHERE</span> encounters.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a><span class="co">-- CTE to hold CHF patient blood pressure (BP) observations where BP is abnormal/out-of-range --</span></span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>, CHF_bp <span class="kw">as</span> (</span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> CHF_encounters.patient, observations.<span class="fu">value</span>, observations.description</span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a>  <span class="kw">FROM</span> CHF_encounters</span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a>  <span class="kw">LEFT</span> <span class="kw">JOIN</span> observations <span class="kw">on</span> CHF_encounters.patient <span class="op">=</span> observations.patient</span>
<span id="cb29-27"><a href="#cb29-27" aria-hidden="true" tabindex="-1"></a>  <span class="kw">WHERE</span> observations.description <span class="kw">LIKE</span> <span class="st">'%Systolic Blood Pressure%'</span></span>
<span id="cb29-28"><a href="#cb29-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-29"><a href="#cb29-29" aria-hidden="true" tabindex="-1"></a><span class="co">-- returns average systolic BP of CHF cohort --</span></span>
<span id="cb29-30"><a href="#cb29-30" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">AVG</span>(<span class="fu">CAST</span>(CHF_bp.<span class="fu">value</span> <span class="kw">as</span> <span class="dt">NUMERIC</span>)) <span class="kw">as</span> avg_sbp</span>
<span id="cb29-31"><a href="#cb29-31" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> CHF_bp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table class="table table-sm table-striped">
<caption>1 records</caption>
<thead>
<tr class="header">
<th style="text-align: right;">avg_sbp</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">149.254</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- CHF patient population CTE used above --</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="kw">WITH</span> CHF_patients <span class="kw">AS</span> (</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> careplans </span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> careplans.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span> <span class="kw">OR</span> careplans.reasoncode <span class="op">=</span> <span class="st">'88805009'</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">UNION</span> </span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> conditions </span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> conditions.description <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>  <span class="kw">UNION</span> </span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>   <span class="kw">SELECT</span> <span class="kw">distinct</span>(patient) </span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>      <span class="kw">FROM</span> notes</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>      <span class="kw">WHERE</span> notes.note_text <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a><span class="co">-- CTE to extract CHF patient encounters --</span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>, CHF_encounters <span class="kw">as</span> (</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>  <span class="kw">SELECT</span> <span class="kw">distinct</span>(CHF_patients.patient), encounters.description, encounters.encounterclass</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>  <span class="kw">FROM</span> CHF_patients</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>  <span class="kw">LEFT</span> <span class="kw">JOIN</span> encounters <span class="kw">on</span> encounters.patient <span class="op">=</span> CHF_patients.patient</span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>  <span class="kw">WHERE</span> encounters.reasondescription <span class="kw">LIKE</span> <span class="st">'%congestive heart failure%'</span></span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a><span class="co">-- CTE to hold CHF patient blood pressure (BP) observations where BP is abnormal/out-of-range --</span></span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a>, CHF_bp <span class="kw">as</span> (</span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> CHF_encounters.patient, observations.<span class="fu">value</span>, observations.description</span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a>  <span class="kw">FROM</span> CHF_encounters</span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a>  <span class="kw">LEFT</span> <span class="kw">JOIN</span> observations <span class="kw">on</span> CHF_encounters.patient <span class="op">=</span> observations.patient</span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a>  <span class="kw">WHERE</span> observations.description <span class="kw">LIKE</span> <span class="st">'%Diastolic Blood Pressure%'</span></span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a><span class="co">-- returns average diastolic BP of CHF cohort --</span></span>
<span id="cb30-30"><a href="#cb30-30" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="fu">AVG</span>(<span class="fu">CAST</span>(CHF_bp.<span class="fu">value</span> <span class="kw">as</span> <span class="dt">NUMERIC</span>)) <span class="kw">as</span> avg_dbp </span>
<span id="cb30-31"><a href="#cb30-31" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> CHF_bp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="knitsql-table">
<table class="table table-sm table-striped">
<caption>1 records</caption>
<thead>
<tr class="header">
<th style="text-align: right;">avg_dbp</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">76.76237</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Target systolic blood pressure (SBP) for heart failure patients is between 110mmHg and 130mmHg. Target diastolic blood pressure (DBP) for heart failure patients is less than or equal to 90mmHg. When CHF patient blood pressure is out of target range, the heart patients are at greater risk for adverse events and admission to the hospital. Of the 847 CHF patient cohort, 791 patients have a systolic blood pressure observation greater than 130mmHg, less than 110mmHg, or a diastolic blood pressure reading greater than/equal to 90mmHg which indicates uncontrolled blood pressure for CHF patients (Huang, Rihua et al, 2022). It is also important to note that the average SBP of our cohort, ~149mmHg is greater than the target SBP upper range 130mmHg. However, the average DBP recorded per CHF patient is within the target DBP for heart failure patients (less than 90mmHg). These patients will need to be targeted for additional care management and may benefit from a nutrition counseling appointment in order to work towards blood pressure control through non-pharmaceutical methods, thus preventing CHF symptom exacerbation in the future.</p>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>Characterizing the health system’s CHF patient cohort above - specifically looking at patient demographics (age, gender, and ethnicity), patient behaviors (smoking), blood pressure control, body weight management, rates of CHF symptom exacerbation, and ED visits - our team has identified patients who may benefit from additional care management and nutrition counseling intervention to prevent future ED visits. Seeing high incidence of emergency department visits and abnormal patient observations in our CHF cohort, we can see a need for intervention regarding dietary care plan compliance. This cohort provides a meaningful patient population for our team identify patient trends and provide reason to hospital administration for quality improvement of CHF patient care.</p>
</section>
<section id="references" class="level3">
<h3 class="anchored" data-anchor-id="references">References</h3>
<p>Abshire, Martha et al.&nbsp;“Nutritional Interventions in Heart Failure: A Systematic Review of the Literature.” Journal of cardiac failure vol.&nbsp;21,12 (2015): 989-99. doi:10.1016/j.cardfail.2015.10.004</p>
<p>American Heart Association. “Heart Failure.” Www.heart.org, 2019 https://www.heart.org/en/health-topics/heart-failure.</p>
<p>American Hospital Association. “Fact Sheet: Majority of Hospital Payments Dependent on Medicare or Medicaid: AHA.” American Hospital Association, 2020, https://www.aha.org/fact-sheets/2022-05-25-fact-sheet-majority-hospital-payments-dependent-medicare-or-medicaid.</p>
<p>Bhatnagar, Roshni, et al.&nbsp;“Expenditure on Heart Failure in the United States: The Medical Expenditure Panel Survey 2009-2018.” JACC, 1 Aug.&nbsp;2022, https://www.jacc.org/doi/abs/10.1016/j.jchf.2022.05.006.</p>
<p>Centers for Disease Control and Prevention. “Heart Failure.” Heart Disease, Centers for Disease Control and Prevention, 14 Oct.&nbsp;2022, https://www.cdc.gov/heartdisease/heart_failure.htm.</p>
<p>Huang, Rihua et al.&nbsp;“Time in Target Range for Systolic Blood Pressure and Cardiovascular Outcomes in Patients With Heart Failure With Preserved Ejection Fraction.” Journal of the American Heart Association vol.&nbsp;11,7 (2022): e022765. doi:10.1161/JAHA.121.022765</p>
<p>“Hospital Readmissions Reduction Program (HRRP).” CMS, 2019, https://www.cms.gov/Medicare/Medicare-Fee-for-Service Payment/AcuteInpatientPPS/Readmissions-Reduction-Program.</p>
<p>Tsuyuki et al.&nbsp;“Acute Precipitants of Congestive Heart Failure Exacerbations.” Archives of internal medicine. 161. (2001): 2337-42. 10.1001/archinte.161.19.2337.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>